### ISSUE TITLE
Update Sites Favicon

### ISSUE THREAD

**Issue by Parker-Bartlett** [Ohio-Elixir/ohio_elixir#8]
## General Description

We don't currently have a favicon set up in our application, this leaves a blank space in the browsers tab when visiting. I've mocked up a generic Ohio border favicon for this issue, but feel free to come up with your own icon if feeling inspired.

![ohio-elixir-mockup](https://user-images.githubusercontent.com/39575797/135957633-254c7b39-5844-4eeb-a5cc-bdcbce28c282.png)

This PNG would need to be converted to an ico, there are a couple of tools available on the web for doing this. Github doesn't support uploading ico files or I would've included that version.

https://realfavicongenerator.net/

**Comment by JenningsF** [comment]
@Parker-Bartlett Can I take a crack at this? Still new to open source contribution, but seems simple enough.

**Comment by Parker-Bartlett** [comment]
closed via #17
